name: Deploy Flask App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /home/ubuntu/FEBE

            sudo apt update
            sudo apt install -y python3-venv

            python3 -m venv venv

            ./venv/bin/pip install -r requirements.txt

            nohup ./venv/bin/python app.py > app.log 2>&1 &

            echo "Flask application started"
